sudo: false
language: scala
jdk: openjdk8
script: sbt +test
matrix:
  include:
    - env: PLAY_VERSION=2.5
    - env: PLAY_VERSION=2.6
    - env: PLAY_VERSION=2.7
cache:
  directories:
    - '$HOME/.ivy2/cache'
notifications:
  email: false
